version: '3.6'

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=spring_boot_demo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=demo_user
      - MYSQL_PASSWORD=demodemo
      - TZ=Asia/Tokyo
    volumes:
      - ./data/db:/var/lib/mysql
      - type: bind
        source:  ./containers/mysql/my.cnf
        target: /etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
